### ISSUE TITLE
incorrect predictions

### ISSUE THREAD

**Issue by heyfey** [justin0u0/NTHU-OAuth-Decaptcha#2] opened 2023-01-05 16:30 UTC
Hi @justin0u0,

The extension worked fine at first but started giving incorrect captcha predictions recently, could you take a look?

Thanks!

https://user-images.githubusercontent.com/19587790/210831136-353dbaa2-6eef-423a-9f97-16f85cdb88cf.mp4

**Comment by justin0u0** [comment] 2023-01-06 02:22
Hi @heyfey, thank you for the report.

They seem to have changed their implementation. Now given the same captcha id, the image will not be same anymore.

We will investigate the issue ASAP and let you know when the fix is available.

**Comment by justin0u0** [comment] 2023-01-07 02:07
Hi @heyfey, the root cause of this issue is that our decaptcha server will send requests to get images using the same captcha ID and the user's session. The image will remain unchanged in the past.

But now they have changed their implementation so that every request sent using the same captcha ID will refresh the actual captcha code. So what we get in the server is the new captcha code, but the one shown on the browser remains stale.

https://user-images.githubusercontent.com/38185674/211125785-d893ea20-0bb7-4b0b-9263-540dbb177b03.mp4

You can see that in the video above, **directly sending the captcha code that the plugin filled in can log in to the system**. So you can ignore the mismatch between the code and the image for now.

We are investigating a new approach to solve this issue, but we still need some time.

Thanks!

**Comment by justin0u0** [comment] 2023-01-14 04:10
Fixed in v1.3.

**Closed as completed by justin0u0** 2023-01-14 04:10 UTC
Labels: bug

**Comment by heyfey** [comment] 2023-01-14 09:46
Hi @justin0u0 ,

Thanks for your help! The tool works well now.
